language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3.5"

install:
  - pip install --editable .[dev,travis]

script:
  - pytest tests/ --cov oscpy/ --cov-branch
  - travis_retry coveralls
