matrix:
  include:
    - os: linux
      sudo: required
      python: 3.4
      env: TOXENV=py34
    - os: linux
      sudo: required
      python: 3.5
      env: TOXENV=py35
    - os: linux
      sudo: required
      python: 3.6
      env: TOXENV=py36
    - os: linux
      dist: xenial
      sudo: required
      python: 3.7
      sudo: true
      env: TOXENV=py37
    - os: linux
      dist: xenial
      sudo: required
      python: 3.8-dev
      sudo: true
      env: TOXENV=py38-dev

    - os: osx
      language: generic
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py34
    - os: osx
      language: generic
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py36

install:
  - pip install --user --editable .[dev,travis]

script:
  - pytest tests/ --cov oscpy/ --cov-branch
  - travis_retry coveralls
