matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8-dev
      dist: xenial
      sudo: true
    - python: pypy3.5

install:
  - pip install --editable .[dev,travis]

script:
  - pytest tests/ --cov oscpy/ --cov-branch
  - travis_retry coveralls
